#!/bin/bash
{
set -e
mkdir /tmp/install_lock
ip route show | grep default > defroute
sudo dhclient eth1 || echo "ignore interfaces which don't exist.."
sudo dhclient -x eth2 || echo "ignore interfaces which don't exist.."
sudo ip route change $(cat defroute)
 # need to know how many interfaces are really needed - aimed at virtualised hosts really...
# this is so that subsequent subnet probes find assigned IP addresses
sudo yum -q  -y install epel-release deltarpm
sudo yum -q  -y install python-netifaces python-pip # python-ipaddress python-colorama # colorama and ipaddress not available in Centos7 epel?
sudo pip install py2-ipaddress colorama # not needed if the RPMs have the packages...

set -a # this ensures the variables set in the next step are exported to subsequent commands...
source config
$(./role.py)
if [[ $OPENSTACK_INSTALL == "yes" ]] ; then
  echo "Local configuration detected and valid role found"
  echo "Will now commence installation"
else
  echo -e "\e[31mNo local configuration detected or no valid role found"
  echo -e "Will abort installation\e[0m"
  exit
fi
sudo -E bash -ev package.sh
source services
sudo systemctl stop $NETWORK_SERVICES $COMPUTE_SERVICES $CONTROLLER_SERVICES
sudo -E bash -ev preflight.sh
if [[ $MY_ROLE =~ "controller" ]] ; then
  echo "running controller node setup"
  sudo -E bash -ev mysql.sh
  sudo -E bash -ev keystone.sh
  sudo -E bash -ev glance.sh
  sudo -E bash -ev cinder.sh
  if [ -n "$INSTALL_HORIZON" ]; then sudo -E bash -ev horizon.sh ; fi
fi
sudo -E bash -ev nova.sh
sudo -E bash -ev neutron.sh
if [ -n "$ODL_IP" ]; then bash -ev odl.sh ; elif
   [ -n "$CALICO" ]; then sudo -E bash -ev calico.sh ; fi
}
rmdir /tmp/install_lock
echo "all complete... :-)"
