#!/bin/bash
set -e
echo centos:centos | sudo chpasswd
sudo sed -i -e '/^PasswordAuthentication/ s/no/yes/' /etc/ssh/sshd_config
sudo systemctl restart sshd
sed -i -e '/requiretty/ d' /etc/sudoers
sudo yum -y install epel-release
sudo yum -y install ntp yum-plugin-priorities
# sudo systemctl disable firewalld ; sudo systemctl stop firewalld
sudo systemctl enable ntpd
sudo systemctl start ntpd
sudo setenforce 0
sudo sed -i 's/enforcing/disabled/g' /etc/selinux/config
