#!/bin/bash
set -e
useradd -d /home/centos -m centos 
echo centos:centos | chpasswd 
printf 'centos ALL=(ALL) NOPASSWD: ALL\n' >> /etc/sudoers
sed -i -e '/requiretty/ d' /etc/sudoers
sed -i -e '/^PasswordAuthentication/ s/no/yes/' /etc/ssh/sshd_config
sudo -u centos mkdir  -m 0700 /home/centos/.ssh
printf "StrictHostKeyChecking No\n" >> /home/centos/.ssh/config
chmod og-rwx /home/centos/.ssh/config
systemctl restart sshd
#cp ceph.repo /etc/yum.repos.d
printf "[main]\nenabled=0\n" > /etc/yum/pluginconf.d/fastestmirror.conf
yum -y install ntp yum-plugin-priorities sshpass
yum -y install epel-release
yum -y remove NetworkManager # selinux-policy-targeted selinux-policy
systemctl --now enable ntpd
setenforce 0
sudo sed -i 's/enforcing/disabled/g' /etc/selinux/config
#yum -y install ceph-deploy
