#!/bin/bash
{
echo "centos:centos" | sudo chpasswd
set +e
mkdir -p /tmp/install_lock

set -a # this ensures the variables set in the next step are exported to subsequent commands...
source config
if [ -n "$LOCALREPO" ]
  then
    sudo yum -q  -y install epel-release deltarpm
  else
    sudo rm -rf /etc/yum.repos.d/*
    sudo cp local.repo /etc/yum.repos.d/
fi

ip route show | grep default > defroute
sudo dhclient eth1
sudo ip link set dev eth2 up
sudo dhclient -x eth2
sudo ip route change $(cat defroute)
set -e
 # need to know how many interfaces are really needed - aimed at virtualised hosts really...
# this is so that subsequent subnet probes find assigned IP addresses
sudo yum -q  -y install python-netifaces python-pip # python-ipaddress python-colorama # colorama and ipaddress not available in Centos7 epel?
sudo pip install py2-ipaddress colorama # not needed if the RPMs have the packages...
$(./role.py)
if [[ $OPENSTACK_INSTALL == "yes" ]] ; then
  echo "Local configuration detected and valid role found"
  echo "Will now commence installation"
else
  echo -e "\e[31mNo local configuration detected or no valid role found"
  echo -e "Will abort installation\e[0m"
  exit
fi
if [ -n "$CALICO" ]; then sudo -E bash -ev calico-package.sh ; fi
sudo -E bash -ev package.sh
source services
sudo systemctl stop $NETWORK_SERVICES $COMPUTE_SERVICES $CONTROLLER_SERVICES
sudo -E bash -ev preflight.sh
if [[ $MY_ROLE =~ "controller" ]] ; then
  echo "running controller node setup"
  sudo -E bash -ev mysql.sh
  sudo -E bash -ev keystone.sh
  sudo -E bash -ev glance.sh
  sudo -E bash -ev cinder.sh
  if [ -n "$INSTALL_HORIZON" ]; then sudo -E bash -ev horizon.sh ; fi
fi
sudo -E bash -ev nova.sh
sudo -E bash -ev neutron.sh
if [ -n "$ODL_IP" ]; then bash -ev odl.sh ; elif
   [ -n "$CALICO" ]; then sudo -E bash -ev calico.sh ; fi
}
rmdir /tmp/install_lock
echo "all complete... :-)"
